roadmap_data = {
    "python": {
        "id": "python",
        "name": "Python",
        "icon": "🐍",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_Rmvb1RYR-iTA_hzckhdONtSW4",
        "about": "Python is a high-level, general-purpose programming language known for its clean syntax and readability. It powers data science, machine learning, web development, and automation, making it the go-to language for AI engineers.",
        "days": [
            {
                "label": "Day 1",
                "topics": [
                    "Print Function",
                    "Data Types in Python",
                    "Comments in Python",
                    "Variables in Python",
                    "Keywords and Identifiers",
                    "Taking user input in Python",
                    "Type conversion in Python",
                    "Literals in Python",
                    "Operators in Python",
                ]
            },
            {
                "label": "Day 2",
                "topics": [
                    "If-else in Python",
                    "Indentation in Python",
                    "While loop",
                    "For Loop",
                    "Nested Loops",
                    "Break, continue and pass statements",
                    "Built-in Functions",
                    "Built-in modules",
                    "Strings and String Operations",
                ]
            },
            {
                "label": "Day 3",
                "topics": [
                    "Python List",
                    "Python Tuples",
                    "Python Sets",
                    "Python Dictionary",
                ]
            },
            {
                "label": "Day 4",
                "topics": [
                    "Python Deep Dive",
                    "Functions in Python",
                ]
            },
            {
                "label": "Day 5",
                "topics": [
                    "Recursions in Python",
                    "Lambda Functions in Python",
                ]
            },
            {
                "label": "Day 6 & 7",
                "topics": [
                    "Complete understanding of OOP in Python",
                    "Threading in Python",
                ]
            },
            {
                "label": "Day 8",
                "topics": [
                    "Iterators",
                    "Generators",
                ]
            },
            {
                "label": "Day 9",
                "topics": [
                    "Complete understanding of GUI in Python",
                ]
            },
            {
                "label": "Day 10 to 15",
                "topics": [
                    "Solve 20 questions of Python each day from the given GitHub repository (Day 10)",
                    "Solve 20 questions of Python each day from the given GitHub repository (Day 11)",
                    "Solve 20 questions of Python each day from the given GitHub repository (Day 12)",
                    "Solve 20 questions of Python each day from the given GitHub repository (Day 13)",
                    "Solve 20 questions of Python each day from the given GitHub repository (Day 14)",
                    "Solve 20 questions of Python each day from the given GitHub repository (Day 15)",
                ]
            },
        ]
    },

    "machine-learning": {
        "id": "machine-learning",
        "name": "Machine Learning",
        "icon": "🤖",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH",
        "about": "Machine Learning is a branch of AI that enables computers to learn patterns from data without being explicitly programmed. It underpins recommendation systems, fraud detection, image recognition, and virtually every modern AI application.",
        "days": [
            {"label": "Day 1", "topics": ["Machine Learning Basics"]},
            {"label": "Day 2", "topics": ["More Machine Learning Basics up to installing Anaconda"]},
            {"label": "Day 3", "topics": ["Framing a Machine Learning problem", "Data collection"]},
            {"label": "Day 4 to 7", "topics": ["Complete Feature Engineering", "PCA"]},
            {"label": "Day 8", "topics": ["Simple Linear Regression"]},
            {"label": "Day 9", "topics": ["Multiple Linear Regression"]},
            {"label": "Day 10 & 11", "topics": ["Gradient Descent"]},
            {"label": "Day 12", "topics": ["Polynomial Regression", "Bias Variance Trade-off"]},
            {"label": "Day 13", "topics": ["Ridge Regression"]},
            {"label": "Day 14", "topics": ["Lasso Regression", "ElasticNet Regression"]},
            {"label": "Day 15 & 16", "topics": ["Logistic Regression"]},
            {"label": "Day 17", "topics": ["Accuracy and Confusion Matrix", "Precision, Recall and F1 Score"]},
            {"label": "Day 18", "topics": ["ROC Curve", "Softmax Regression"]},
            {"label": "Day 19", "topics": ["Polynomial features in Logistic Regression", "Logistic Regression Hyperparameters"]},
            {"label": "Day 20", "topics": ["Naive Bayes", "KNN"]},
            {"label": "Day 21", "topics": ["SVM"]},
            {"label": "Day 22", "topics": ["Decision Trees"]},
            {"label": "Day 23", "topics": ["Ensemble Learning", "Voting Ensembles", "Bagging"]},
            {"label": "Day 24", "topics": ["Random Forest"]},
            {"label": "Day 25", "topics": ["Adaboost Classifier"]},
            {"label": "Day 26", "topics": ["Gradient Boosting"]},
            {"label": "Day 27", "topics": ["XGBoost"]},
            {"label": "Day 28", "topics": ["K-Means Clustering"]},
            {"label": "Day 29", "topics": ["Agglomerative Hierarchical Clustering"]},
            {"label": "Day 30", "topics": ["DBSCAN Clustering"]},
        ]
    },

    "deep-learning": {
        "id": "deep-learning",
        "name": "Deep Learning",
        "icon": "🧠",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvYuZauWaPlRTC54KxSNLtNn",
        "about": "Deep Learning uses multi-layered neural networks to learn complex representations from raw data like images, audio, and text. It is the technology behind face recognition, self-driving cars, voice assistants, and large language models.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Deep Learning",
                "Biological Neuron vs Artificial Neuron",
                "History of Neural Networks",
                "Applications of Deep Learning",
                "Deep Learning vs Machine Learning",
            ]},
            {"label": "Day 2", "topics": [
                "Perceptron — structure and working",
                "Perceptron Learning Algorithm",
                "Multi-Layer Perceptron (MLP)",
                "Forward Propagation",
                "Activation Functions — Sigmoid, ReLU, Tanh",
            ]},
            {"label": "Day 3", "topics": [
                "Loss Functions — MSE, Cross Entropy",
                "Backpropagation — chain rule",
                "Gradient Descent in Neural Networks",
                "Vanishing and Exploding Gradients",
            ]},
            {"label": "Day 4", "topics": [
                "Optimizers — SGD, Momentum, RMSProp",
                "Adam and AdaGrad Optimizers",
                "Learning Rate Scheduling",
                "Weight Initialization Techniques",
            ]},
            {"label": "Day 5", "topics": [
                "Overfitting and Underfitting in Deep Learning",
                "Dropout Regularization",
                "Batch Normalization",
                "Early Stopping",
                "L1 and L2 Regularization in Neural Networks",
            ]},
            {"label": "Day 6", "topics": [
                "Introduction to CNNs",
                "Convolution Operation",
                "Padding and Stride",
                "Pooling Layers — Max and Average Pooling",
                "Building a CNN from scratch",
            ]},
            {"label": "Day 7", "topics": [
                "Classic CNN Architectures — LeNet, AlexNet",
                "VGGNet Architecture",
                "GoogLeNet / Inception Architecture",
                "Feature Maps and Visualization",
            ]},
            {"label": "Day 8", "topics": [
                "ResNet — Residual Connections",
                "Transfer Learning Concept",
                "Fine-tuning Pretrained Models",
                "Data Augmentation for Images",
            ]},
            {"label": "Day 9", "topics": [
                "Object Detection — YOLO, SSD",
                "Image Segmentation — Semantic vs Instance",
                "U-Net Architecture",
                "Introduction to Generative Models",
            ]},
            {"label": "Day 10", "topics": [
                "Autoencoders — structure and types",
                "Variational Autoencoders (VAE)",
                "Applications of Autoencoders",
                "Denoising Autoencoders",
            ]},
            {"label": "Day 11", "topics": [
                "Generative Adversarial Networks (GANs) — concept",
                "GAN Training — Generator and Discriminator",
                "Deep Convolutional GAN (DCGAN)",
                "GAN challenges — mode collapse, training instability",
            ]},
            {"label": "Day 12", "topics": [
                "Introduction to RNNs",
                "Vanishing Gradient in RNNs",
                "LSTM — architecture and gates",
                "GRU — Gated Recurrent Unit",
            ]},
            {"label": "Day 13", "topics": [
                "Sequence-to-Sequence Models",
                "Encoder-Decoder Architecture",
                "Attention Mechanism in Seq2Seq",
                "Beam Search Decoding",
            ]},
            {"label": "Day 14", "topics": [
                "Introduction to Transformers",
                "Self-Attention and Multi-Head Attention",
                "Positional Encoding",
                "Transformer Encoder and Decoder Blocks",
            ]},
            {"label": "Day 15", "topics": [
                "BERT — Bidirectional Encoder Representations",
                "GPT Architecture Overview",
                "Vision Transformer (ViT)",
                "Diffusion Models — overview",
                "Deep Learning Project End-to-End walkthrough",
            ]},
        ]
    },

    "transformer": {
        "id": "transformer",
        "name": "Transformer Architecture",
        "icon": "⚡",
        "status": "not started",
        "playlist": None,
        "playlist_note": "100 Days of Deep Learning — Lecture 80 to Lecture 84",
        "about": "The Transformer architecture is the foundational model behind GPT, BERT, and virtually all modern LLMs. It introduced the self-attention mechanism, replacing RNNs to process sequences in parallel — enabling today's generative AI breakthroughs.",
        "days": [
            {"label": "Lecture 80", "topics": [
                "Limitations of RNNs and motivation for Transformers",
                "Attention is All You Need — paper overview",
                "Scaled Dot-Product Attention",
                "Query, Key and Value vectors",
            ]},
            {"label": "Lecture 81", "topics": [
                "Multi-Head Attention — concept and computation",
                "Positional Encoding — sinusoidal and learned",
                "Feed-Forward layers in Transformer",
                "Residual Connections and Layer Normalization",
            ]},
            {"label": "Lecture 82", "topics": [
                "Transformer Encoder block — full architecture",
                "Transformer Decoder block — masked self-attention",
                "Cross-Attention between Encoder and Decoder",
                "Teacher Forcing in training",
            ]},
            {"label": "Lecture 83", "topics": [
                "BERT — Masked Language Modelling and NSP",
                "GPT — Autoregressive language modelling",
                "T5 — Text-to-Text Transfer Transformer",
                "Fine-tuning vs Prompting",
            ]},
            {"label": "Lecture 84", "topics": [
                "Vision Transformer (ViT) — patch embeddings",
                "CLIP — Contrastive Language-Image Pretraining",
                "Transformer scaling laws",
                "Modern LLM architectures — LLaMA, Mistral overview",
            ]},
        ]
    },

    "pytorch": {
        "id": "pytorch",
        "name": "PyTorch / TensorFlow",
        "icon": "🔥",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_Rmvboy8bmDCjwNHgTaYH2puK7",
        "about": "PyTorch is a flexible deep learning framework widely used in research and production. TensorFlow is Google's production-grade ML platform. Together they are the two dominant frameworks for building, training, and deploying neural network models.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to PyTorch — why PyTorch",
                "Installing PyTorch and setting up environment",
                "Tensors — creation, types and operations",
                "Tensor vs NumPy array",
                "GPU support — moving tensors to CUDA",
            ]},
            {"label": "Day 2", "topics": [
                "Autograd — automatic differentiation",
                "Computational Graphs in PyTorch",
                "requires_grad, backward() and grad",
                "Gradient accumulation and zeroing",
            ]},
            {"label": "Day 3", "topics": [
                "Building Neural Networks with nn.Module",
                "Linear Layers, Activation Functions in nn",
                "Forward method and model summary",
                "Loss Functions — nn.CrossEntropyLoss, nn.MSELoss",
                "Optimizers — torch.optim.SGD, Adam",
            ]},
            {"label": "Day 4", "topics": [
                "Dataset and DataLoader classes",
                "Custom Dataset — __len__ and __getitem__",
                "Data Transforms with torchvision.transforms",
                "Train/Val/Test splits with DataLoader",
            ]},
            {"label": "Day 5", "topics": [
                "Complete Training Loop — forward, loss, backward, step",
                "Validation Loop and tracking metrics",
                "Saving and Loading model weights",
                "torch.save and torch.load",
                "Checkpointing models",
            ]},
            {"label": "Day 6", "topics": [
                "Building a CNN in PyTorch",
                "Conv2d, MaxPool2d, Flatten layers",
                "Training CNN on image classification dataset",
                "Using torchvision datasets — MNIST, CIFAR-10",
            ]},
            {"label": "Day 7", "topics": [
                "Transfer Learning with torchvision models",
                "Fine-tuning ResNet / VGG",
                "Freezing and unfreezing layers",
                "TensorBoard integration for tracking",
                "Introduction to TensorFlow and Keras comparison",
            ]},
        ]
    },

    "nlp": {
        "id": "nlp",
        "name": "NLP Fundamentals",
        "icon": "💬",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvZo7fp5kkIth6nRTeQQsjfX",
        "about": "Natural Language Processing (NLP) is the field of AI focused on enabling machines to understand, interpret, and generate human language. It powers chatbots, sentiment analysis, machine translation, search engines, and text summarization.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to NLP and its applications",
                "Text Preprocessing — Tokenization",
                "Stopword Removal and Stemming",
                "Lemmatization",
                "Regular Expressions for text cleaning",
            ]},
            {"label": "Day 2", "topics": [
                "Bag of Words (BoW) model",
                "TF-IDF — Term Frequency Inverse Document Frequency",
                "N-gram models",
                "Text Vectorization with CountVectorizer and TfidfVectorizer",
                "Text Classification with BoW and TF-IDF",
            ]},
            {"label": "Day 3", "topics": [
                "Word Embeddings — motivation and concept",
                "Word2Vec — Skip-gram and CBOW",
                "GloVe — Global Vectors for Word Representation",
                "FastText Embeddings",
                "Visualizing embeddings with t-SNE",
            ]},
            {"label": "Day 4", "topics": [
                "RNNs for text data",
                "Sentiment Analysis with RNN",
                "Sequence Padding and Masking",
                "Bidirectional RNNs",
                "Text Generation with RNN",
            ]},
            {"label": "Day 5", "topics": [
                "LSTM for NLP tasks",
                "Named Entity Recognition (NER)",
                "Part-of-Speech Tagging",
                "Sequence Labelling with LSTM",
            ]},
            {"label": "Day 6", "topics": [
                "Introduction to BERT for NLP",
                "Tokenization with Hugging Face Tokenizers",
                "Fine-tuning BERT for text classification",
                "Question Answering with BERT",
            ]},
            {"label": "Day 7", "topics": [
                "Text Summarization — extractive vs abstractive",
                "Machine Translation overview",
                "Topic Modelling — LDA",
                "Spacy for NLP pipelines",
                "End-to-end NLP project walkthrough",
            ]},
        ]
    },

    "rag": {
        "id": "rag",
        "name": "RAG",
        "icon": "🔍",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_Rmva0dRLWEHLznSHKbFD_RJfX",
        "about": "Retrieval-Augmented Generation (RAG) combines a language model with a vector search engine to ground responses in real documents. It is used to build Q&A systems, document chatbots, and knowledge bases that stay accurate and up-to-date.",
        "days": [
            {"label": "Day 1", "topics": [
                "What is Retrieval-Augmented Generation (RAG)",
                "Problems RAG solves — hallucination, outdated knowledge",
                "RAG vs Fine-tuning",
                "RAG pipeline overview — Retrieval + Generation",
                "Use cases of RAG",
            ]},
            {"label": "Day 2", "topics": [
                "Document Loading — PDF, Web, CSV loaders",
                "Text Splitting strategies — fixed size, recursive",
                "Chunk size and overlap tuning",
                "Metadata handling in documents",
            ]},
            {"label": "Day 3", "topics": [
                "Text Embeddings — dense vs sparse",
                "OpenAI and HuggingFace Embedding models",
                "Vector Stores — FAISS, Chroma, Pinecone",
                "Indexing and storing document chunks",
            ]},
            {"label": "Day 4", "topics": [
                "Similarity Search — cosine, dot product, euclidean",
                "Top-k retrieval",
                "MMR — Maximal Marginal Relevance",
                "Hybrid Search — keyword + semantic",
            ]},
            {"label": "Day 5", "topics": [
                "Building a basic RAG pipeline end-to-end",
                "Prompt engineering for RAG",
                "Context window management",
                "RetrievalQA chain with LangChain",
            ]},
            {"label": "Day 6", "topics": [
                "Advanced RAG — HyDE (Hypothetical Document Embeddings)",
                "Multi-query Retrieval",
                "Parent-Child Chunking strategy",
                "Re-ranking retrieved documents",
                "Contextual Compression",
            ]},
            {"label": "Day 7", "topics": [
                "RAG Evaluation — RAGAS framework",
                "Faithfulness, Answer Relevancy, Context Recall metrics",
                "Agentic RAG overview",
                "RAG with structured data",
                "Production RAG considerations",
            ]},
        ]
    },

    "langchain": {
        "id": "langchain",
        "name": "Gen AI using LangChain",
        "icon": "🦜",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvaTbihpo4MtzVm4XOQa0ER0",
        "about": "LangChain is a framework for building applications powered by large language models. It provides chains, agents, memory, and tool integrations that let you connect LLMs to APIs, databases, and external data sources with minimal boilerplate.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to LangChain and ecosystem",
                "Setting up LangChain environment",
                "LangChain vs direct API calls",
                "LLM wrappers — OpenAI, Anthropic, Ollama",
                "Basic LLM call with LangChain",
            ]},
            {"label": "Day 2", "topics": [
                "Prompt Templates — PromptTemplate, ChatPromptTemplate",
                "System and Human message templates",
                "Few-shot Prompt Templates",
                "Output Parsers — StrOutputParser, JSON parser",
            ]},
            {"label": "Day 3", "topics": [
                "LangChain Expression Language (LCEL)",
                "Chaining with | operator",
                "RunnablePassthrough and RunnableLambda",
                "Batch and stream invocations",
            ]},
            {"label": "Day 4", "topics": [
                "Memory types — ConversationBufferMemory",
                "ConversationSummaryMemory",
                "ConversationBufferWindowMemory",
                "Adding memory to chains",
                "Chat history management",
            ]},
            {"label": "Day 5", "topics": [
                "Document Loaders — PDF, Web, Text, CSV",
                "Text Splitters — RecursiveCharacterTextSplitter",
                "Embedding models in LangChain",
                "Vector stores — Chroma, FAISS with LangChain",
            ]},
            {"label": "Day 6", "topics": [
                "Retrieval chains in LangChain",
                "create_retrieval_chain",
                "create_stuff_documents_chain",
                "Conversational RAG chain",
                "History-aware retriever",
            ]},
            {"label": "Day 7", "topics": [
                "LangChain Tools — built-in and custom",
                "Introduction to Agents",
                "ReAct Agent",
                "Tool calling with LLMs",
                "Agent executor",
            ]},
            {"label": "Day 8", "topics": [
                "LangGraph introduction",
                "Nodes, Edges and State in LangGraph",
                "Building a simple graph agent",
                "Conditional edges and branching",
            ]},
            {"label": "Day 9", "topics": [
                "LangSmith for tracing and debugging",
                "Evaluating LangChain apps",
                "Streaming responses",
                "Structured output with LLMs",
                "Pydantic output parsers",
            ]},
            {"label": "Day 10", "topics": [
                "End-to-end Conversational RAG app with LangChain",
                "Multi-tool Agent project",
                "Deployment with FastAPI and LangChain",
                "Best practices and production tips",
            ]},
        ]
    },

    "mlops": {
        "id": "mlops",
        "name": "ML OPS",
        "icon": "⚙️",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvaKHYjy5v0dJh8edeaEWb-b",
        "about": "MLOps (Machine Learning Operations) applies DevOps principles to the ML lifecycle — covering model versioning, experiment tracking, CI/CD pipelines, deployment, monitoring, and reproducibility. It bridges the gap between data science and production engineering.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to MLOps — what and why",
                "MLOps vs DevOps",
                "ML lifecycle — data, training, evaluation, deployment, monitoring",
                "Experiment Tracking with MLflow",
                "Model Registry and versioning",
                "CI/CD for Machine Learning pipelines",
                "Model Serving — REST API, batch, streaming",
                "Model Monitoring — data drift, concept drift",
                "Feature Stores — concept and use",
                "Introduction to tools — DVC, Prefect, Airflow",
            ]},
        ]
    },

    "claude-code": {
        "id": "claude-code",
        "name": "Claude Code (Agentic Coding)",
        "icon": "🤖",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvaYH3poI0oJvbDF4zEvpq8W",
        "about": "Claude Code is Anthropic's AI-powered agentic coding tool that can read, write, and reason about entire codebases. It enables developers to automate complex engineering tasks, refactor code, write tests, and ship features using natural language.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Claude Code",
                "Installing and setting up Claude Code CLI",
                "First conversation and basic commands",
                "Understanding Claude Code's capabilities",
                "CLAUDE.md — project context file",
            ]},
            {"label": "Day 2", "topics": [
                "File reading, editing and writing with Claude Code",
                "Running shell commands via Claude Code",
                "Navigating and exploring codebases",
                "Asking questions about existing code",
            ]},
            {"label": "Day 3", "topics": [
                "Agentic coding — multi-step autonomous tasks",
                "Todo tracking in Claude Code",
                "Debugging workflows with Claude Code",
                "Writing and running tests",
            ]},
            {"label": "Day 4", "topics": [
                "Working with Git using Claude Code",
                "Creating commits and pull requests",
                "Code review with Claude Code",
                "Refactoring large codebases",
            ]},
            {"label": "Day 5", "topics": [
                "MCP — Model Context Protocol overview",
                "Setting up MCP servers",
                "Connecting external tools via MCP",
                "Custom slash commands",
            ]},
            {"label": "Day 6", "topics": [
                "Building a full project with Claude Code",
                "Multi-file project management",
                "Claude Code in VS Code extension",
                "Hooks and automation",
            ]},
            {"label": "Day 7", "topics": [
                "Claude Code best practices",
                "Security and permission modes",
                "Claude Code for data science workflows",
                "Advanced agentic patterns",
                "Real-world project walkthrough",
            ]},
        ]
    },

    "hugging-face": {
        "id": "hugging-face",
        "name": "Hugging Face",
        "icon": "🤗",
        "status": "not started",
        "playlist": None,
        "about": "Hugging Face is the hub of the open-source AI community, hosting thousands of pre-trained models, datasets, and Spaces. Its Transformers library lets you fine-tune and deploy state-of-the-art NLP, vision, and multimodal models in just a few lines of code.",
        "days": []
    },

    "ollama": {
        "id": "ollama",
        "name": "Ollama",
        "icon": "🦙",
        "status": "not started",
        "playlist": "https://youtu.be/YcAYmIFtA0o?si=SYIU_OrirSL7BMW",
        "about": "Ollama lets you run open-source large language models (LLaMA, Mistral, Gemma, and more) entirely on your local machine with a single command. It exposes a REST API compatible with OpenAI's interface, making local LLM integration straightforward.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Ollama — run LLMs locally",
                "Installing Ollama on Mac/Linux/Windows",
                "Pulling and running models — llama3, mistral, gemma",
                "ollama run, ollama list, ollama pull commands",
                "Ollama REST API — /api/generate and /api/chat",
                "Using Ollama with Python requests library",
                "Connecting Ollama to LangChain",
                "Connecting Ollama to Open WebUI",
                "Model customization with Modelfile",
                "Running multimodal models locally with Ollama",
            ]},
        ]
    },

    "fastapi": {
        "id": "fastapi",
        "name": "FastAPI",
        "icon": "🚀",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvZ41tjbKB2ZnwchfniNsMuQ",
        "about": "FastAPI is a modern, high-performance Python web framework for building REST APIs. It uses Python type hints to auto-generate interactive documentation and validate requests, making it the preferred choice for serving ML models and building AI backends.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to FastAPI — why FastAPI",
                "Installing FastAPI and Uvicorn",
                "First FastAPI app — Hello World",
                "Automatic docs — Swagger UI and ReDoc",
                "HTTP methods — GET, POST, PUT, DELETE",
            ]},
            {"label": "Day 2", "topics": [
                "Path Parameters and type hints",
                "Query Parameters",
                "Optional and default parameters",
                "Multiple path and query parameters",
                "Parameter validation",
            ]},
            {"label": "Day 3", "topics": [
                "Request Body with Pydantic models",
                "Nested Pydantic models",
                "Field validation with Pydantic",
                "Request Body + Path + Query together",
                "Response models and status codes",
            ]},
            {"label": "Day 4", "topics": [
                "Database integration with SQLAlchemy",
                "Creating database models",
                "CRUD operations — Create, Read, Update, Delete",
                "Dependency Injection in FastAPI",
                "Database sessions as dependencies",
            ]},
            {"label": "Day 5", "topics": [
                "Authentication with OAuth2",
                "JWT tokens — creation and verification",
                "Password hashing with passlib",
                "Protecting routes with dependencies",
                "Role-based access control",
            ]},
            {"label": "Day 6", "topics": [
                "Background Tasks in FastAPI",
                "File Upload and download",
                "Static files serving",
                "Middleware — CORS, logging",
                "WebSockets with FastAPI",
            ]},
            {"label": "Day 7", "topics": [
                "Testing FastAPI with pytest and TestClient",
                "Error handling and HTTPException",
                "Environment variables with dotenv",
                "Deploying FastAPI with Docker",
                "FastAPI + ML model deployment walkthrough",
            ]},
        ]
    },

    "docker": {
        "id": "docker",
        "name": "Docker",
        "icon": "🐳",
        "status": "not started",
        "playlist": "https://youtu.be/GToyQTGDOS4?si=PYIaOjcdnoiaUEzi",
        "about": "Docker packages applications and their dependencies into lightweight, portable containers that run consistently across any environment. It is essential for deploying ML models and AI services reliably from a laptop to the cloud.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Docker — containers vs virtual machines",
                "Docker architecture — daemon, client, registry",
                "Installing Docker",
                "Docker Images and Containers",
                "docker run, docker ps, docker stop, docker rm",
                "Dockerfile — writing your first Dockerfile",
                "Building images with docker build",
                "Docker Hub — pushing and pulling images",
                "Docker Volumes — persistent data",
                "Docker Networks — container communication",
                "Docker Compose — multi-container apps",
                "Dockerizing a Python/FastAPI application",
            ]},
        ]
    },

    "n8n": {
        "id": "n8n",
        "name": "N8N",
        "icon": "🔗",
        "status": "not started",
        "playlist": "https://youtu.be/LGqaSsSLz68?si=8WSGyedc-25qBjPv",
        "about": "N8N is a powerful open-source workflow automation tool that connects apps, APIs, and AI models through a visual node editor. It lets you build complex automations — from data pipelines to AI agent workflows — without writing boilerplate code.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to N8N — no-code automation",
                "Installing N8N — local and cloud",
                "N8N interface — canvas, nodes, workflows",
                "Trigger nodes — Webhook, Schedule, Manual",
                "Action nodes — HTTP Request, Email, Slack",
                "Connecting nodes and passing data",
                "Expressions and variables in N8N",
                "AI Agent node in N8N",
                "Connecting N8N to LLMs (OpenAI, Anthropic)",
                "Building an AI-powered automation workflow",
                "Error handling and workflow debugging",
            ]},
        ]
    },

    "github": {
        "id": "github",
        "name": "Git & GitHub",
        "icon": "🐙",
        "status": "not started",
        "playlist": "https://youtu.be/tRctqKXhoow?si=QGNHMthlTFlOS3Zb",
        "about": "Git is the industry-standard version control system that tracks every change in your codebase. GitHub adds collaboration on top — pull requests, code review, and CI/CD. Every developer and data scientist needs Git & GitHub from day one.",
        "days": [
            {"label": "Day 1", "topics": [
                "What is version control and why it matters",
                "Installing Git and initial configuration",
                "git init — creating a repository",
                "git status, git add, git commit",
                "git log — viewing commit history",
                "Undoing changes — git restore, git reset",
                "Branching — git branch, git checkout, git switch",
                "Merging branches — git merge",
                "Resolving merge conflicts",
                "Introduction to GitHub — creating an account and a repo",
            ]},
            {"label": "Day 2", "topics": [
                "Connecting local repo to GitHub — git remote, git push",
                "Cloning a repository — git clone",
                "git pull vs git fetch",
                "Fork and Pull Request workflow",
                "GitHub Issues and project boards",
                ".gitignore — ignoring files",
                "GitHub Actions overview — CI/CD basics",
                "git stash — saving work in progress",
                "Tags and releases on GitHub",
                "Best practices — commit messages, branching strategies",
            ]},
        ]
    },

    "maths-for-ml": {
        "id": "maths-for-ml",
        "name": "Maths for ML",
        "icon": "📐",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvbYFaaeLY28cWeqV-3vADST",
        "about": "Machine learning is built on mathematics. This roadmap covers the three pillars — Linear Algebra, Calculus, and Statistics & Probability — giving you the intuition and tools to understand every ML algorithm from scratch.",
        "days": [
            {"label": "Day 1", "topics": [
                "Why Maths matters in Machine Learning",
                "Overview of Linear Algebra, Calculus and Statistics",
                "Scalars, Vectors and their geometric interpretation",
                "Vector addition, scalar multiplication",
                "Dot product and its geometric meaning",
            ]},
            {"label": "Day 2", "topics": [
                "Matrices — definition, types and notation",
                "Matrix addition and scalar multiplication",
                "Matrix multiplication — rules and intuition",
                "Transpose of a matrix",
                "Identity matrix and zero matrix",
            ]},
            {"label": "Day 3", "topics": [
                "Inverse of a matrix",
                "Solving systems of linear equations with matrices",
                "Rank of a matrix",
                "Linear independence of vectors",
                "Span and basis of a vector space",
            ]},
            {"label": "Day 4", "topics": [
                "Determinant of a matrix",
                "Geometric interpretation of determinant",
                "Trace of a matrix",
                "Norms — L1, L2, and Frobenius norms",
                "Orthogonal matrices and projections",
            ]},
            {"label": "Day 5", "topics": [
                "Eigenvalues and Eigenvectors — concept and computation",
                "Eigendecomposition",
                "Symmetric matrices and their properties",
                "Positive Definite matrices",
                "Application of eigenvalues in ML",
            ]},
            {"label": "Day 6", "topics": [
                "Singular Value Decomposition (SVD) — concept",
                "SVD vs Eigendecomposition",
                "Principal Component Analysis (PCA) via SVD",
                "Dimensionality reduction intuition",
                "Low-rank approximation of matrices",
            ]},
            {"label": "Day 7", "topics": [
                "Introduction to Calculus for ML",
                "Limits and continuity",
                "Derivatives — definition and rules",
                "Power rule, product rule, quotient rule",
                "Chain rule — the backbone of backpropagation",
            ]},
            {"label": "Day 8", "topics": [
                "Partial derivatives — functions of multiple variables",
                "Gradient vector — direction of steepest ascent",
                "Gradient Descent intuition",
                "Directional derivatives",
                "Total derivative",
            ]},
            {"label": "Day 9", "topics": [
                "Jacobian matrix — vector-valued functions",
                "Hessian matrix — second-order derivatives",
                "Convexity and concavity of functions",
                "Local and global minima",
                "Saddle points in optimization",
            ]},
            {"label": "Day 10", "topics": [
                "Taylor Series expansion",
                "Newton's method for optimization",
                "Lagrange multipliers — constrained optimization",
                "Integration basics — area under a curve",
                "Monte Carlo integration concept",
            ]},
            {"label": "Day 11", "topics": [
                "Introduction to Statistics and Probability",
                "Descriptive statistics — mean, median, mode",
                "Variance, standard deviation, range",
                "Percentiles and quartiles",
                "Data visualization in statistics — histograms, box plots",
            ]},
            {"label": "Day 12", "topics": [
                "Sample space, events and probability",
                "Axioms of probability",
                "Conditional probability — P(A|B)",
                "Independence of events",
                "Bayes' Theorem and its applications in ML",
            ]},
            {"label": "Day 13", "topics": [
                "Random variables — discrete and continuous",
                "Probability Mass Function (PMF)",
                "Probability Density Function (PDF)",
                "Cumulative Distribution Function (CDF)",
                "Expected value and variance of a random variable",
            ]},
            {"label": "Day 14", "topics": [
                "Common distributions — Bernoulli, Binomial",
                "Poisson distribution",
                "Uniform distribution",
                "Gaussian (Normal) distribution — bell curve",
                "Standard Normal and Z-scores",
            ]},
            {"label": "Day 15", "topics": [
                "Central Limit Theorem — why it matters",
                "Sampling distributions",
                "Confidence intervals",
                "Hypothesis testing — null and alternate hypothesis",
                "p-value and significance level",
            ]},
            {"label": "Day 16", "topics": [
                "t-test — one sample and two sample",
                "Chi-square test",
                "ANOVA — Analysis of Variance",
                "Type I and Type II errors",
                "Statistical power",
            ]},
            {"label": "Day 17", "topics": [
                "Covariance — measuring joint variability",
                "Pearson Correlation coefficient",
                "Spearman Rank Correlation",
                "Covariance matrix",
                "Multicollinearity in data",
            ]},
            {"label": "Day 18", "topics": [
                "Maximum Likelihood Estimation (MLE)",
                "Log-likelihood and its optimization",
                "MAP estimation — Maximum A Posteriori",
                "Prior, Likelihood and Posterior",
                "MLE applied to linear regression",
            ]},
            {"label": "Day 19", "topics": [
                "Information Theory basics",
                "Entropy — measuring uncertainty",
                "Cross-Entropy — loss function in classification",
                "KL Divergence — comparing distributions",
                "Mutual Information",
            ]},
            {"label": "Day 20", "topics": [
                "Maths review — end-to-end walkthrough",
                "How linear algebra powers neural networks",
                "How calculus enables backpropagation",
                "How probability underpins Naive Bayes and Bayesian ML",
                "Practice problems covering all three pillars",
            ]},
        ]
    },

    "sql": {
        "id": "sql",
        "name": "SQL",
        "icon": "🗄️",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvYun1_5r9Fb4eQigioPB7yn",
        "about": "SQL (Structured Query Language) is the universal language for querying and managing relational databases. Data scientists and ML engineers use SQL daily to extract, filter, aggregate, and join datasets before feeding them into models.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to databases and SQL",
                "Relational databases — tables, rows, columns",
                "Installing MySQL / using SQLite",
                "SELECT statement — fetching data",
                "WHERE clause — filtering rows",
                "Comparison and logical operators — AND, OR, NOT",
                "ORDER BY — sorting results",
                "LIMIT and OFFSET — pagination",
                "DISTINCT — removing duplicates",
                "Basic string and numeric functions",
            ]},
            {"label": "Day 2", "topics": [
                "Aggregate functions — COUNT, SUM, AVG, MIN, MAX",
                "GROUP BY — grouping rows",
                "HAVING — filtering grouped results",
                "INNER JOIN — combining tables",
                "LEFT, RIGHT and FULL OUTER JOIN",
                "SELF JOIN and CROSS JOIN",
                "Subqueries — nested SELECT",
                "IN, EXISTS, ANY, ALL operators",
                "CREATE TABLE, INSERT, UPDATE, DELETE",
                "PRIMARY KEY, FOREIGN KEY, UNIQUE constraints",
            ]},
            {"label": "Day 3", "topics": [
                "Window functions — ROW_NUMBER, RANK, DENSE_RANK",
                "LEAD and LAG functions",
                "PARTITION BY with window functions",
                "Common Table Expressions (CTEs) — WITH clause",
                "Recursive CTEs",
                "Indexes — what they are and when to use them",
                "Views — virtual tables",
                "Stored procedures and triggers overview",
                "SQL for data analysis — practical queries",
                "SQL interview patterns — top N, running totals, duplicates",
            ]},
        ]
    },

    "numpy": {
        "id": "numpy",
        "name": "NumPy",
        "icon": "🔢",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_Rmvb-ToL3RQ_bwxG4_ND-0-DT",
        "about": "NumPy is the foundation of Python's scientific computing stack. It provides the high-performance n-dimensional array object and the vectorized mathematical operations that power pandas, scikit-learn, TensorFlow, and PyTorch under the hood.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to NumPy and why it is faster than lists",
                "Installing NumPy",
                "ndarray — the core data structure",
                "Creating arrays — np.array, np.zeros, np.ones, np.eye",
                "Array data types — dtype",
                "Shape, size, ndim and nbytes attributes",
            ]},
            {"label": "Day 2", "topics": [
                "Array creation functions — np.arange, np.linspace, np.logspace",
                "Random arrays — np.random.rand, randn, randint",
                "Seeding random number generation",
                "Reshaping arrays — reshape, flatten, ravel",
                "Transposing arrays — .T attribute",
            ]},
            {"label": "Day 3", "topics": [
                "Array indexing — 1D, 2D and 3D",
                "Slicing arrays — start:stop:step",
                "Boolean indexing — filtering arrays",
                "Fancy indexing — index arrays",
                "np.where — conditional selection",
            ]},
            {"label": "Day 4", "topics": [
                "Element-wise arithmetic operations",
                "Broadcasting rules — operating on different shapes",
                "Universal functions (ufuncs) — np.add, np.multiply",
                "Comparison operators on arrays",
                "np.clip — bounding values",
            ]},
            {"label": "Day 5", "topics": [
                "Aggregation functions — sum, mean, std, var, min, max",
                "Axis parameter — row-wise vs column-wise operations",
                "np.cumsum and np.cumprod",
                "np.argmin and np.argmax — index of extremes",
                "np.unique — unique values and counts",
            ]},
            {"label": "Day 6", "topics": [
                "Matrix operations — np.dot, np.matmul",
                "np.linalg.inv — matrix inverse",
                "np.linalg.det — determinant",
                "np.linalg.eig — eigenvalues and eigenvectors",
                "np.linalg.svd — Singular Value Decomposition",
                "Solving linear systems — np.linalg.solve",
            ]},
            {"label": "Day 7", "topics": [
                "Stacking arrays — np.vstack, np.hstack, np.concatenate",
                "Splitting arrays — np.split, np.vsplit, np.hsplit",
                "np.tile and np.repeat",
                "Sorting arrays — np.sort, np.argsort",
                "Structured arrays overview",
            ]},
            {"label": "Day 8", "topics": [
                "String operations with np.char",
                "Working with datetime — np.datetime64",
                "Saving and loading arrays — np.save, np.load, np.savetxt",
                "Memory layout — C-order vs F-order",
                "Views vs copies in NumPy",
            ]},
            {"label": "Day 9", "topics": [
                "Vectorization vs loops — performance comparison",
                "np.vectorize — applying functions element-wise",
                "np.apply_along_axis",
                "Masked arrays — np.ma",
                "Numerical precision and floating-point issues",
            ]},
            {"label": "Day 10", "topics": [
                "NumPy for ML — feature matrix construction",
                "Normalisation and standardisation with NumPy",
                "Implementing linear regression from scratch with NumPy",
                "Implementing softmax and sigmoid with NumPy",
                "End-to-end NumPy mini project — data analysis",
            ]},
        ]
    },

    "pandas": {
        "id": "pandas",
        "name": "Pandas",
        "icon": "🐼",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvbR85fgbfVRKOiMokUKVupy",
        "about": "Pandas is the go-to Python library for data manipulation and analysis. Built on NumPy, it provides DataFrame and Series objects that make loading, cleaning, transforming, and exploring tabular data fast and expressive.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Pandas — Series and DataFrame",
                "Creating Series from lists, dicts and NumPy arrays",
                "Creating DataFrames — from dicts, lists and CSV",
                "Reading files — pd.read_csv, pd.read_excel, pd.read_json",
                "DataFrame attributes — shape, dtypes, index, columns",
                "head(), tail(), info(), describe()",
            ]},
            {"label": "Day 2", "topics": [
                "Selecting columns — single and multiple",
                "Selecting rows — loc (label-based) and iloc (position-based)",
                "Boolean indexing — filtering rows",
                "Setting and resetting index",
                "Renaming columns and index",
                "Dropping rows and columns — drop()",
            ]},
            {"label": "Day 3", "topics": [
                "Handling missing values — isnull, notnull",
                "fillna — filling missing values",
                "dropna — dropping missing values",
                "Detecting and removing duplicate rows",
                "Data type conversion — astype()",
                "String operations with .str accessor",
            ]},
            {"label": "Day 4", "topics": [
                "Adding and modifying columns",
                "apply() — applying functions to rows and columns",
                "map() and applymap() / map() on DataFrame",
                "replace() — replacing values",
                "Sorting — sort_values(), sort_index()",
                "Ranking with rank()",
            ]},
            {"label": "Day 5", "topics": [
                "GroupBy — split, apply, combine",
                "Aggregation with groupby — sum, mean, count, agg",
                "Pivot tables — pd.pivot_table",
                "Crosstab — pd.crosstab",
                "Melt — wide to long format",
                "Stack and unstack",
            ]},
            {"label": "Day 6", "topics": [
                "Merging DataFrames — pd.merge (inner, left, right, outer)",
                "Joining DataFrames — .join()",
                "Concatenating — pd.concat along rows and columns",
                "Handling duplicate keys after merge",
                "Time series basics — pd.to_datetime",
                "Resampling and rolling windows",
            ]},
            {"label": "Day 7", "topics": [
                "Plotting with Pandas — df.plot()",
                "Window functions — rolling, expanding, ewm",
                "Categorical data type in Pandas",
                "Memory optimisation — downcasting dtypes",
                "Reading large files — chunksize",
                "End-to-end EDA project with Pandas",
            ]},
        ]
    },

    "seaborn": {
        "id": "seaborn",
        "name": "Seaborn",
        "icon": "📊",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvbB1bFGjvS6a8T0mnqawejo",
        "about": "Seaborn is a Python statistical data visualisation library built on Matplotlib. It makes it easy to create attractive, informative plots — heatmaps, pair plots, violin plots, and regression plots — with minimal code, essential for EDA in any data science workflow.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Seaborn and Matplotlib basics",
                "Seaborn figure styles and colour palettes",
                "sns.histplot — distribution of a single variable",
                "sns.kdeplot — Kernel Density Estimate",
                "sns.ecdfplot — cumulative distribution",
                "sns.rugplot — marginal ticks",
                "sns.displot — unified distribution plot API",
            ]},
            {"label": "Day 2", "topics": [
                "sns.scatterplot — relationships between two variables",
                "sns.lineplot — trends over time",
                "sns.relplot — figure-level scatter and line",
                "sns.regplot — scatter with regression line",
                "sns.lmplot — regression with grouping",
                "sns.residplot — residuals of a regression",
                "Adding hue, size and style for a third variable",
            ]},
            {"label": "Day 3", "topics": [
                "sns.barplot — estimated value with confidence interval",
                "sns.countplot — frequency of categories",
                "sns.boxplot — distribution with quartiles and outliers",
                "sns.violinplot — KDE + boxplot combined",
                "sns.stripplot and sns.swarmplot",
                "sns.catplot — figure-level categorical API",
                "sns.pointplot — connected point estimates",
            ]},
            {"label": "Day 4", "topics": [
                "sns.heatmap — correlation matrices and pivot tables",
                "sns.clustermap — hierarchically clustered heatmap",
                "sns.pairplot — all pairwise relationships",
                "sns.PairGrid — customisable pair grid",
                "sns.FacetGrid — multi-panel conditional plots",
                "Customising Seaborn plots — titles, labels, ticks",
                "Combining Seaborn with Matplotlib for fine-grained control",
                "End-to-end EDA visualisation project",
            ]},
        ]
    },

    "opencv": {
        "id": "opencv",
        "name": "OpenCV",
        "icon": "👁️",
        "status": "not started",
        "playlist": "https://www.youtube.com/playlist?list=PLKnIA16_RmvYXDBJ5WRDuQRSzFJs93pYR",
        "about": "OpenCV (Open Source Computer Vision Library) is the most widely used library for real-time image and video processing. It covers everything from basic image transformations to advanced feature detection, object tracking, and integrating deep learning models for vision tasks.",
        "days": [
            {"label": "Day 1", "topics": [
                "Introduction to Computer Vision and OpenCV",
                "Installing OpenCV — pip install opencv-python",
                "Reading, displaying and saving images — cv2.imread, imshow, imwrite",
                "Image as a NumPy array — shape, dtype",
                "Accessing and modifying individual pixels",
                "BGR vs RGB — colour channel order in OpenCV",
            ]},
            {"label": "Day 2", "topics": [
                "Colour space conversions — BGR to Grayscale, HSV, LAB",
                "cv2.cvtColor — converting between colour spaces",
                "Splitting and merging colour channels",
                "Colour thresholding in HSV space",
                "Colour detection and masking",
            ]},
            {"label": "Day 3", "topics": [
                "Image resizing — cv2.resize",
                "Cropping images with array slicing",
                "Flipping images — cv2.flip",
                "Rotating images — cv2.rotate and getRotationMatrix2D",
                "Affine transformations — translation, scaling, shear",
                "Perspective transformation — cv2.getPerspectiveTransform",
            ]},
            {"label": "Day 4", "topics": [
                "Drawing lines — cv2.line",
                "Drawing rectangles — cv2.rectangle",
                "Drawing circles and ellipses",
                "Drawing polygons — cv2.polylines, fillPoly",
                "Putting text on images — cv2.putText",
                "Working with fonts and text size",
            ]},
            {"label": "Day 5", "topics": [
                "Image blurring — Averaging, Gaussian blur",
                "Median blur — noise removal",
                "Bilateral filter — edge-preserving smoothing",
                "Custom kernel convolution — cv2.filter2D",
                "Sharpening images with kernels",
            ]},
            {"label": "Day 6", "topics": [
                "Image thresholding — cv2.threshold",
                "Adaptive thresholding — mean and Gaussian",
                "Otsu's binarisation — automatic threshold selection",
                "Inverse thresholding",
                "Thresholding for document scanning",
            ]},
            {"label": "Day 7", "topics": [
                "Gradient detection — Sobel, Scharr, Laplacian",
                "Canny edge detection — cv2.Canny",
                "Tuning Canny thresholds",
                "Edge detection applications",
                "Image gradients for feature extraction",
            ]},
            {"label": "Day 8", "topics": [
                "Morphological operations — erosion, dilation",
                "Opening and closing",
                "Morphological gradient and top-hat transforms",
                "Structuring elements — rectangular, elliptical, cross",
                "Applications — noise removal, text extraction",
            ]},
            {"label": "Day 9", "topics": [
                "Finding contours — cv2.findContours",
                "Drawing contours — cv2.drawContours",
                "Contour properties — area, perimeter, bounding box",
                "Contour approximation — cv2.approxPolyDP",
                "Convex hull",
                "Shape detection using contour properties",
            ]},
            {"label": "Day 10", "topics": [
                "Image histograms — cv2.calcHist",
                "Histogram visualisation with Matplotlib",
                "Histogram equalisation — cv2.equalizeHist",
                "CLAHE — Contrast Limited Adaptive Histogram Equalisation",
                "Histogram back-projection for object tracking",
            ]},
            {"label": "Day 11", "topics": [
                "Harris Corner Detection",
                "Shi-Tomasi corner detection — cv2.goodFeaturesToTrack",
                "SIFT — Scale-Invariant Feature Transform",
                "ORB — Oriented FAST and Rotated BRIEF",
                "Feature matching — BFMatcher, FLANN",
                "Homography and image stitching overview",
            ]},
            {"label": "Day 12", "topics": [
                "Template matching — cv2.matchTemplate",
                "Haar cascade classifiers — face detection",
                "Loading and using pre-trained Haar cascades",
                "Eye and smile detection with cascades",
                "Limitations of Haar cascades",
            ]},
            {"label": "Day 13", "topics": [
                "Video capture — cv2.VideoCapture",
                "Reading frames in a loop",
                "Saving video — cv2.VideoWriter",
                "Real-time processing pipeline",
                "FPS measurement and optimisation",
                "Webcam-based colour and motion detection",
            ]},
            {"label": "Day 14", "topics": [
                "Optical flow — Lucas-Kanade method",
                "Dense optical flow — Farneback",
                "Background subtraction — MOG2, KNN",
                "Object tracking — cv2.TrackerCSRT, KCF",
                "Motion detection application",
            ]},
            {"label": "Day 15", "topics": [
                "Deep learning with OpenCV — cv2.dnn module",
                "Loading ONNX and Caffe models",
                "Running inference on images",
                "Real-time face detection with DNN",
                "OpenCV + YOLO object detection",
                "End-to-end project — face blur and object counter",
            ]},
        ]
    },
}

skills_order = [
    "python",
    "github",
    "maths-for-ml",
    "sql",
    "numpy",
    "pandas",
    "seaborn",
    "machine-learning",
    "deep-learning",
    "pytorch",
    "transformer",
    "nlp",
    "opencv",
    "hugging-face",
    "rag",
    "langchain",
    "ollama",
    "fastapi",
    "docker",
    "mlops",
    "claude-code",
    "n8n",
]
